Traceback (most recent call last):
  File "MLR_TEST_LOG.py", line 23, in <module>
    file = dict_[i.split("_")[1]]
KeyError: 'D'
